apiVersion: v1
kind: Service
metadata:
  labels:
    app: mosquitto
  name: mosquitto
spec:
  ports:
  - port: 1883
    targetPort: mqtt
    protocol: TCP
    name: mqtt
  - port: 9001
    targetPort: websocket
    protocol: TCP
    name: websocket
  selector:
    app: mosquitto

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mosquitto
  name: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: "eclipse-mosquitto:2.0.15"
        imagePullPolicy: IfNotPresent
        ports:
        - name: mqtt
          containerPort: 1883
          protocol: TCP
        - name: websocket
          containerPort: 9001
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: mqtt
        readinessProbe:
          tcpSocket:
            port: mqtt
        volumeMounts:
        # Mount config where the Docker image expects it to be.
        # See:
        # - https://github.com/eclipse/mosquitto/tree/master/docker/2.0
        - name: mosquitto-config
          mountPath: /mosquitto/config
        # Mount persistent storage on the volume the Docker image defines.
        # See:
        # - https://github.com/eclipse/mosquitto/tree/master/docker/2.0
        - name: mosquitto-volume
          mountPath: /mosquitto/data
      volumes:
      - name: mosquitto-config
        configMap:
          name: mosquitto-config
      - name: mosquitto-volume
        persistentVolumeClaim:
          claimName: mosquitto-pvc
