apiVersion: v1
kind: PersistentVolume
metadata:
  name: emoj-backend-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: emoj-backend-pvc
  hostPath:
    path: "/home/ubuntu/Desktop/media/video"
    type: DirectoryOrCreate


