apiVersion: v1
kind: Service
metadata:
  labels:
    app: emoj-db
  name: emoj-db
spec:
  ports:
  # PostgreSQL wire protocol clients.
  - port: 5432
    targetPort: 5432
    name: emoj-db
  selector:
    app: emoj-db

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: emoj-db
  labels:
    app: emoj-db
  annotations:
    # Tell Reloader to bounce the Argo CD server whenever the SSO config
    # and built-in admin credentials change.
    secret.reloader.stakater.com/reload: "emoj-secret"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emoj-db
  template:
    metadata:
      labels:
        app: emoj-db
    spec:
      containers:
      - name: emoj-db
        image: postgres:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: emoj-secret
              key: postgresemoj.password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: pg-emoj-volume
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pg-emoj-volume
        persistentVolumeClaim:
          claimName: emoj-db-pvc
