apiVersion: v1
kind: Service
metadata:
  labels:
    app: emoj-backend
  name: emoj-backend
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: emoj-backend

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: emoj-backend
  name: emoj-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emoj-backend
  template:
    metadata:
      labels:
        app: emoj-backend
    spec:
      containers:
        - image: 768927817436.dkr.ecr.eu-south-1.amazonaws.com/kitt4sme-hego:latest
          imagePullPolicy: Always
          name: emoj-backend
          ports:
          - containerPort: 5000
            name: http
          env:
          - name: AWS_ACCOUNT
            valueFrom:
              secretKeyRef:
                name: emoj-secret
                key: aws.account
          - name: AWS_REGION
            valueFrom:
              secretKeyRef:
                name: emoj-secret
                key: aws.region
          - name: POSTGRES_HOST
            value: "emoj-db"
          - name: EMOJ_BACKEND
            value: "http://emoj-backend:5000"
          - name: "ORION_BASE_URL"
            value: "http://orion:1026"
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: emoj-secret
                key: postgreshego.password
          - name: VIDEO_PATH
            value: "/app/videos"
          volumeMounts:
            - mountPath: /app/videos
              name: emoj-backend-pvc
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: emoj-backend-pvc
          persistentVolumeClaim:
            claimName: emoj-backend-pvc
